apiVersion : apps/v1
kind: Deployment
metadata:
  name: "agoravai-1b8c"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "agoravai-1b8c"
  template:
    metadata:
      labels:
        app: "agoravai-1b8c"
    spec:
      containers:
        - name: "agoravai-1b8c"
          image: "wellingtonsantos022021acr.azurecr.io/agoravai"
          ports:
          - containerPort: 80