apiVersion: v1
kind: Service
metadata:
    name: "agoravai-1b8c"
    labels:
        app: "agoravai-1b8c"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "agoravai-1b8c"