on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: wellingtonsantos022021acr.azurecr.io
        username: ${{ secrets.acr_wellingtonsantos022021acr_username }}
        password: ${{ secrets.acr_wellingtonsantos022021acr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "dockerfile" -t wellingtonsantos022021acr.azurecr.io/agoravai:${{ github.sha }} --label dockerfile-path=dockerfile
        docker push wellingtonsantos022021acr.azurecr.io/agoravai:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_agoravai_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep agora-vai9ba4 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace agora-vai9ba4`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: agora-vai9ba4
        container-registry-url: wellingtonsantos022021acr.azurecr.io
        container-registry-username: ${{ secrets.acr_wellingtonsantos022021acr_username }}
        container-registry-password: ${{ secrets.acr_wellingtonsantos022021acr_password }}
        secret-name: agoravaidockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: agora-vai9ba4
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          wellingtonsantos022021acr.azurecr.io/agoravai:${{ github.sha }}
        imagepullsecrets: |
          agoravaidockerauth
